"""Add new fields to Page model

Revision ID: 7cebdaa6ec3c
Revises: 18852db59474
Create Date: 2026-01-31 15:37:40.719367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cebdaa6ec3c'
down_revision: Union[str, None] = '18852db59474'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('author', sa.String(), nullable=True))
    op.add_column('pages', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('pages', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('pages', sa.Column('language', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pages', 'language')
    op.drop_column('pages', 'image_url')
    op.drop_column('pages', 'summary')
    op.drop_column('pages', 'author')
    # ### end Alembic commands ###
