"""fts_and_performance_indexes

Revision ID: c94ff7832ae5
Revises: e08e1a318180
Create Date: 2026-02-19 00:48:23.519737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c94ff7832ae5'
down_revision: Union[str, None] = 'e08e1a318180'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_page_contents_created_at', 'page_contents', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_page_contents_text_fts', 'page_contents', [sa.literal_column("to_tsvector('spanish', extracted_text)")], unique=False, postgresql_using='gin')
    op.create_index('ix_pages_published_at', 'pages', [sa.literal_column('published_at DESC')], unique=False)
    op.create_index('ix_pages_title_fts', 'pages', [sa.literal_column("to_tsvector('spanish', title)")], unique=False, postgresql_using='gin')
    op.alter_column('sites', 'config_warning',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sites', 'config_warning',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index('ix_pages_title_fts', table_name='pages', postgresql_using='gin')
    op.drop_index('ix_pages_published_at', table_name='pages')
    op.drop_index('ix_page_contents_text_fts', table_name='page_contents', postgresql_using='gin')
    op.drop_index('ix_page_contents_created_at', table_name='page_contents')
    # ### end Alembic commands ###
