"""Add soft delete to sites

Revision ID: db44e8c3e90f
Revises: c94ff7832ae5
Create Date: 2026-02-26 19:36:57.022738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db44e8c3e90f'
down_revision: Union[str, None] = 'c94ff7832ae5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sites', sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sites', 'deleted')
    # ### end Alembic commands ###
