"""add config_warning to sites

Revision ID: e08e1a318180
Revises: 7cebdaa6ec3c
Create Date: 2026-02-06 00:39:26.222508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e08e1a318180'
down_revision: Union[str, None] = '7cebdaa6ec3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Make idempotent: check if column exists
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [c['name'] for c in inspector.get_columns('sites')]
    if 'config_warning' not in columns:
        op.add_column('sites', sa.Column('config_warning', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [c['name'] for c in inspector.get_columns('sites')]
    if 'config_warning' in columns:
        op.drop_column('sites', 'config_warning')
    # ### end Alembic commands ###
